server:
  port: 9001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_streams?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 14400000
      idle-timeout: 300000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: /* ping */ SELECT 1
      leak-detection-threshold: 5000
      auto-commit: true
      keepalive-time: 30000
      initialization-fail-timeout: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

srs:
  server:
    ip: your-srs-server-ip
  app:
    name: live

logging:
  level:
    com.example.live: DEBUG
    com.zaxxer.hikari: DEBUG